@echo off
echo Starting Upskill Backend Server...
echo.
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo.
echo Starting uvicorn server...
python -m uvicorn app.main:app --reload --reload-dir app --host 0.0.0.0 --port 8000
